# Generated by Django 3.2.3 on 2021-08-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_Date',
            new_name='ordered_date',
        ),
    ]
